---
- name: Deploy Spring Boot JAR to EC2
  hosts: all
  become: yes
  collections:
    - amazon.aws
  vars:
    jar_file: spring-petclinic-3.5.0-SNAPSHOT.jar
    remote_path: /home/ec2-user/

  tasks:
    - name: Install Java 17
      package:
        name: java-17-amazon-corretto
        state: present

    - name: Install Nginx
      package:
        name: nginx
        state: present

    - name: Ensure Nginx is started and enabled
      service:
        name: nginx
        state: started
        enabled: true

    - name: Download JAR from S3 to EC2
      amazon.aws.aws_s3:
        bucket: jenkins-s3-prince
        object: spring-petclinic-3.5.0-SNAPSHOT.jar
        dest: /home/ec2-user/spring-petclinic-3.5.0-SNAPSHOT.jar
        mode: get
        overwrite: true

    - name: Kill running Spring Boot app (if any)
      shell: pkill -f "{{ jar_file }}"
      ignore_errors: yes

    - name: Run Spring Boot app in background
      shell: "nohup java -jar {{ remote_path }}{{ jar_file }} > /dev/null 2>&1 &"

    - name: Configure Nginx as reverse proxy
      copy:
        dest: /etc/nginx/conf.d/springboot.conf
        content: |
          server {
              listen 80;
              server_name localhost;

              location / {
                  proxy_pass http://localhost:8080;
                  proxy_set_header Host $host;
                  proxy_set_header X-Real-IP $remote_addr;
                  proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                  proxy_set_header X-Forwarded-Proto $scheme;
              }
          }

    - name: Remove default nginx config
      file:
        path: /etc/nginx/conf.d/default.conf
        state: absent
      ignore_errors: yes

    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded
